import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
    {
        _id: "1",
        productName: "Apple iPhone 13 (128GB, Blue)",
        productDescription: [
            "Display: 6.1 inches (15.4 cm), Super Retina XDR OLED",
            "Memory: 128GB ROM",
            "Processor: Apple A15 Bionic, Hexa Core",
            "Camera: 12 MP + 12 MP Dual Rear & 12 MP Front Camera",
            "Battery: 15W Wireless Charging",
            "Security (Lock): Password | PIN | Face Unlock",
        ],
        productImage:
            "https://d2d22nphq0yz8t.cloudfront.net/88e6cc4b-eaa1-4053-af65-563d88ba8b26/https://media.croma.com/image/upload/v1664009609/Croma%20Assets/Communication/Mobiles/Images/243463_0_qtsxpd.png/mxw_1440,f_auto",
        categoryName: "iphone",
        price: 69900,
        discountPercent: 7,
        discountedPrice: 63990,
        onSale: true,
        outOfStock: false,
        rating: 4.5,
        trending: true,
    },
    {
        _id: "12",
        productName: "Apple iPhone 13 Pro Max (1TB, Gold)",
        productDescription: [
            "Display: 6.1 inches (15.54 cm) OLED Display",
            "Memory: 128GB ROM",
            "Processor: A16 Bionic Chip, Hexa Core",
            "Camera: 48 MP + 12 MP + 12 MP Triple Rear & 12 MP Front Camera",
            "Battery: Qi Wireless Charging Up to 7.5W",
            "Security (Lock): Facial Lock",
        ],
        productImage:
            "https://d2d22nphq0yz8t.cloudfront.net/88e6cc4b-eaa1-4053-af65-563d88ba8b26/https://media.croma.com/image/upload/v1662703105/Croma%20Assets/Communication/Mobiles/Images/261963_oqrd6j.png/mxw_1440,f_auto",
        categoryName: "iphone",
        price: 179900,
        discountPercent: 0,
        discountedPrice: 179900,
        onSale: false,
        outOfStock: false,
        rating: 4.7,
        trending: false,
    },
    {
        _id: "2",
        productName: "Apple iPhone 14 (128GB, Blue) ",
        productDescription: [
            " Display: 6.1 inches (15.40 cm) OLED Display",
            "Memory: 128GB ROM",
            "Processor: A15 Bionic Chip, Hexa Core",
            "Camera: 12 MP + 12 MP Dual Rear & 12 MP Front Camera",
            "Battery: Qi Wireless Charging Up to 7.5W",
            "Security (Lock): Facial Lock",
        ],
        productImage:
            "https://d2d22nphq0yz8t.cloudfront.net/88e6cc4b-eaa1-4053-af65-563d88ba8b26/https://media.croma.com/image/upload/v1662703724/Croma%20Assets/Communication/Mobiles/Images/261934_qgssvy.png/mxw_1440,f_auto",
        categoryName: "iphone",
        price: 79900.0,
        discountPercent: 6,
        discountedPrice: 74900.0,
        onSale: true,
        outOfStock: false,
        rating: 3.8,
        trending: false,
    },
    {
        _id: "3",
        productName: "Apple iPhone 14 Pro (128GB, Deep Purple)",
        productDescription: [
            "Display: 6.1 inches (15.54 cm) OLED Display",
            "Memory: 128GB ROM",
            "Processor: A16 Bionic Chip, Hexa Core",
            "Camera: 48 MP + 12 MP + 12 MP Triple Rear & 12 MP Front Camera",
            "Battery: Qi Wireless Charging Up to 7.5W",
            "Security (Lock): Facial Lock",
        ],
        productImage:
            "https://d2d22nphq0yz8t.cloudfront.net/88e6cc4b-eaa1-4053-af65-563d88ba8b26/https://media.croma.com/image/upload/v1662703105/Croma%20Assets/Communication/Mobiles/Images/261963_oqrd6j.png/mxw_1440,f_auto",
        categoryName: "iphone",
        price: 129900,
        discountPercent: 2,
        discountedPrice: 127490,
        onSale: true,
        outOfStock: false,
        rating: 4.7,
        trending: false,
    },
    {
        _id: "4",
        productName: "OnePlus 10 Pro 5G (12GB RAM, 256GB, Emerald Forest)",
        productDescription: [
            "Display: 6.7 inches (17.01 cm), QHD+ AMOLED, 120 Hz Refresh Rate",
            "Memory: 12GB RAM, 256GB ROM",
            "Processor: Qualcomm Snapdragon 8 Gen 1 , Octa Core 3 GHz",
            "Camera : 48 MP + 50 MP + 8 MP Triple Rear & 32 MP Front Camera",
            "Battery: 5000 mAh with 50W Fast Charging",
            "Security (Lock): In-display Fingerprint Sensor",
        ],
        productImage:
            "https://d2d22nphq0yz8t.cloudfront.net/88e6cc4b-eaa1-4053-af65-563d88ba8b26/https://media.croma.com/image/upload/v1666992109/Croma%20Assets/Communication/Mobiles/Images/250716_rea31a.png/mxw_1440,f_auto",
        categoryName: "android",
        price: 71999,
        discountPercent: 0,
        discountedPrice: 71999,
        onSale: false,
        outOfStock: false,
        rating: 4.9,
        trending: true,
    },
    {
        _id: "5",
        productName: "SAMSUNG Galaxy A34 5G (8GB RAM, 128GB, Awesome Graphite)",
        productDescription: [
            "Display: 6.6 inches (16.65cm), Super AMOLED, 120 Hz Refresh Rate",
            "Memory: 8GB RAM, 128GB ROM, Memory Card (Hybrid) upto 1TB",
            "Processor: Mediatek Dimensity 1080, Octa Core, 2.6 GHz",
            "Camera: 48 MP + 8 MP + 5 MP Triple Rear & 13 MP Front Camera",
            "Battery: 5000 mAh",
            "USP: AI-Image Enhancer",
        ],
        productImage:
            "https://d2d22nphq0yz8t.cloudfront.net/88e6cc4b-eaa1-4053-af65-563d88ba8b26/https://media.croma.com/image/upload/v1681117343/Croma%20Assets/Communication/Mobiles/Images/270482_mm7dlm.png/mxw_1440,f_auto",
        categoryName: "android",
        price: 35499,
        discountPercent: 13,
        discountedPrice: 30999,
        onSale: true,
        outOfStock: false,
        rating: 4.9,
        trending: true,
    },
    {
        _id: "6",
        productName: "vivo Y56 5G (8GB RAM, 128GB, Black Engine)",
        productDescription: [
            "Display: 6.56 inches (16.66 cm), 90 Hz Refresh Rate",
            "Memory: 8GB RAM, 128GB ROM",
            "Processor: Dimensity 700, Octa Core, 2.2 GHz",
            "Camera: 50 MP+ 2 MP Dual Rear & 8 MP Front Camera",
            "Battery: 5000 mAh with 33W SUPERVOOC Charging",
            "Fingerprint Sensor, Facial Recognition",
        ],
        productImage:
            "https://d2d22nphq0yz8t.cloudfront.net/88e6cc4b-eaa1-4053-af65-563d88ba8b26/https://media.croma.com/image/upload/v1683559922/Croma%20Assets/Communication/Mobiles/Images/268555_0_wbrnym.png/mxw_1440,f_auto",
        categoryName: "android",
        price: 24999,
        discountPercent: 20,
        discountedPrice: 19999,
        onSale: true,
        outOfStock: false,
        rating: 4.8,
        trending: true,
    },
    {
        _id: "7",
        productName: "Redmi 10A Sport (6GB RAM, 128GB, Slate Grey)",
        productDescription: [
            "Display: 6.53 inches (16.58 cm), HD Plus Display",
            "Memory: 6GB RAM, 128GB ROM",
            "Processor: MediaTek Helio G25, Octa-Core, 2.0 GHz",
            "Camera : 13 MP Rear & 5 MP Front Camera",
            "Battery: 5000 mAh with 10W Fast charging",
            "Sensor: G-Sensor, L-Sensor, P-Sensor",
        ],
        productImage:
            "https://d2d22nphq0yz8t.cloudfront.net/88e6cc4b-eaa1-4053-af65-563d88ba8b26/https://media.croma.com/image/upload/v1669052468/Croma%20Assets/Communication/Mobiles/Images/260296_0_y6z8zm.png/mxw_1440,f_auto",
        categoryName: "android",
        price: 13999,
        discountPercent: 25,
        discountedPrice: 10499,
        onSale: true,
        outOfStock: false,
        rating: 4.7,
        trending: false,
    },
    {
        _id: "8",
        productName:
            "Nokia 105 12ASTB21A02 (4MB, 800 mAh Battery, FM Radio, Black)",
        productDescription: [
            "SIM: Single",
            "Battery: 800 mAh",
            "Memory: 4MB ROM",
            "FM/Radio: Supports FM/Radio",
        ],
        productImage:
            "https://d2d22nphq0yz8t.cloudfront.net/88e6cc4b-eaa1-4053-af65-563d88ba8b26/https://media.croma.com/image/upload/v1683555747/Croma%20Assets/Communication/Mobiles/Images/250284_0_qmu2ob.png/mxw_1440,f_auto",
        categoryName: "feature phones",
        price: 1349,
        discountPercent: 7,
        discountedPrice: 1249,
        onSale: true,
        outOfStock: false,
        rating: 4.6,
        trending: true,
    },
    {
        _id: "9",
        productName: "Nokia 2660 Flip (128MB, Dual SIM, Rear Camera, Blue)",
        productDescription: [
            "SIM : Dual",
            "Battery: 1450 mAh",
            "Memory: 128MB ROM, Memory Card upto 32GB",
            "Other Features: 0.3 MP Rear Camera, FM Radio, Bluetooth",
        ],
        productImage:
            "https://d2d22nphq0yz8t.cloudfront.net/88e6cc4b-eaa1-4053-af65-563d88ba8b26/https://media.croma.com/image/upload/v1672054293/Croma%20Assets/Communication/Mobiles/Images/260712_0_uzp9lu.png/mxw_1440,f_auto",
        categoryName: "feature phones",
        price: 5699,
        discountPercent: 18,
        discountedPrice: 4699,
        onSale: true,
        outOfStock: true,
        rating: 4.9,
        trending: false,
    },
    {
        _id: "10",
        productName: "Easyfone Royale (32MB, FM Radio, Rear Camera, Blue)",
        productDescription: [
            "SIM: Single",
            "Battery: 700 mAh",
            "Memory: 32MB ROM, microSD Card upto 32GB",
            "Camera: 0.3 MP Rear Camera",
        ],
        productImage:
            "https://d2d22nphq0yz8t.cloudfront.net/88e6cc4b-eaa1-4053-af65-563d88ba8b26/https://media.croma.com/image/upload/v1683560806/Croma%20Assets/Communication/Mobiles/Images/220198_0_ir6iym.png/mxw_1440,f_auto",
        categoryName: "feature phones",
        price: 3999,
        discountPercent: 13,
        discountedPrice: 3499,
        onSale: true,
        outOfStock: true,
        rating: 3.6,
        trending: false,
    },
    {
        _id: "11",
        productName:
            "Saregama Carvaan CM181 (2GB, Dual SIM, Built-in FM, Classic Black)",
        productDescription: [
            "SIM : Dual",
            "Battery : 1800 mAh",
            "Memory : 2GB ROM, Memory Card upto 8GB",
            "Other Features: FM Radio, Bluetooth",
        ],
        productImage:
            "https://d2d22nphq0yz8t.cloudfront.net/88e6cc4b-eaa1-4053-af65-563d88ba8b26/https://media.croma.com/image/upload/v1683556043/Croma%20Assets/Communication/Mobiles/Images/260197_0_s0trej.png/mxw_1440,f_auto",
        categoryName: "feature phones",
        price: 1990,
        discountPercent: 0,
        discountedPrice: 1990,
        onSale: false,
        outOfStock: false,
        rating: 4.6,
        trending: true,
    },
];
