import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: "1",
    productName: "Canon EOS R6",
    productDescription: "Mirrorless Full-Frame Camera",
    productImage:
      "https://images.unsplash.com/photo-1599664223843-9349c75196bc?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    categoryName: "cameras",
    price: 2399,
    discountPercent: 10,
    discountedPrice: 2159,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    _id: "2",
    productName: "Sony FE 16-35mm f/2.8 GM Lens",
    productDescription: "Wide-Angle Zoom Lens for Sony E-mount Cameras",
    productImage:
      "https://www.tanotis.com/cdn/shop/products/sony_sel1635gm_fe_16_35mm_f_2_8_gm_1495038144000_1338516_800x.jpg?v=1576002574",
    categoryName: "lenses",
    price: 2198,
    discountPercent: 0,
    discountedPrice: 2198,
    onSale: false,
    outOfStock: false,
    rating: 3.8,
    trending: false,
  },
  {
    _id: "3",
    productName: "Manfrotto MT055CXPRO4 Carbon Fiber Tripod",
    productDescription: "Professional Tripod with Carbon Fiber Legs",
    productImage:
      "https://cdn.manfrotto.com/media/catalog/product/cache/1e774dca205198565016e92bdb88ad55/m/t/mt055cxpro4.jpg",
    categoryName: "accessories",
    price: 489,
    discountPercent: 0,
    discountedPrice: 489,
    onSale: false,
    outOfStock: false,
    rating: 4.7,
    trending: false,
  },
  {
    _id: "4",
    productName: "GoPro HERO 9 Black",
    productDescription:
      "Waterproof Sports Camera with Front LCD Screen & Rear Touch Screen,5K Ultra HD Video,20MP Photos,1080p Live Streaming, Stabilization-Black",
    productImage:
      "https://static.gopro.com/assets/blta2b8522e5372af40/blt3fe219e4bdfa4a25/643ec271fa6b79233e8d5c90/pdp-h9-image01-1920-2x.png?width=1920&quality=80&auto=webp&disable=upscale",
    categoryName: "cameras",
    price: 450,
    discountPercent: 20,
    discountedPrice: 360,
    onSale: true,
    outOfStock: false,
    rating: 4.9,
    trending: true,
  },
  {
    _id: "5",
    productName: "Nikon D850",
    productDescription:
      "A powerful DSLR camera that features a high-resolution sensor and fast autofocus.",
    productImage:
      "https://cdn-4.nikon-cdn.com/e/Q5NM96RZZo-YRYNeYvAi9beHK4x3L-8h09FYyKWnWU6L2l14O7STBw==/Views/1585_D850_left.png",
    categoryName: "cameras",
    price: 2999,
    discountPercent: 15,
    discountedPrice: 2549,
    onSale: true,
    outOfStock: false,
    rating: 4.9,
    trending: true,
  },
  {
    _id: "6",
    productName: "Canon EF 70-200mm f/2.8L IS III USM Lens",
    productDescription: "Telephoto Zoom Lens for Canon DSLR Cameras",
    productImage: "https://m.media-amazon.com/images/I/61PDQet-AzL._SX522_.jpg",
    categoryName: "lenses",
    price: 2099,
    discountPercent: 0,
    discountedPrice: 2099,
    onSale: false,
    outOfStock: false,
    rating: 4.8,
    trending: true,
  },
  {
    _id: "7",
    productName: "Profoto A1X AirTTL-N Studio Light for Nikon",
    productDescription: "Portable Studio Flash for Nikon Cameras",
    productImage: "https://m.media-amazon.com/images/I/81Myv5AcSeL._SX522_.jpg",
    categoryName: "lighting",
    price: 1099,
    discountPercent: 20,
    discountedPrice: 879,
    onSale: true,
    outOfStock: false,
    rating: 4.7,
    trending: false,
  },
  {
    _id: "8",
    productName: "Lowepro ProTactic BP 450 AW II Camera Backpack",
    productDescription: "Camera Backpack with Customizable Interior",
    productImage:
      "https://cdn.lowepro.com/media/catalog/product/cache/1e774dca205198565016e92bdb88ad55/c/a/camera-backpack-protactic-bp-450-ii-aw-lp37177-stuffeda-rgb.jpg",
    categoryName: "bags",
    price: 249,
    discountPercent: 10,
    discountedPrice: 224,
    onSale: true,
    outOfStock: false,
    rating: 4.6,
    trending: true,
  },
  {
    _id: "9",
    productName: "Sony a7 III",
    productDescription: "Full-Frame Mirrorless Camera",
    productImage: "https://m.media-amazon.com/images/I/91rQ3XfEYzL._SX522_.jpg",
    categoryName: "cameras",
    price: 1999,
    discountPercent: 0,
    discountedPrice: 1999,
    onSale: false,
    outOfStock: true,
    rating: 4.9,
    trending: false,
  },
  {
    _id: "10",
    productName: "Godox SL-60W LED Video Light",
    productDescription:
      "A powerful LED light designed for video and photography, featuring adjustable color temperature, wireless remote control, and quiet fan cooling.",
    productImage: "https://m.media-amazon.com/images/I/61wAYBPWWIL._SX522_.jpg",
    categoryName: "lighting",
    price: 139.0,
    discountPercent: 0,
    discountedPrice: 139.0,
    onSale: false,
    outOfStock: true,
    rating: 3.6,
    trending: false,
  },
  {
    _id: "11",
    productName: "Canon EF 50mm f/1.4 USM Standard Lens",
    productDescription:
      "A fast and sharp lens that is ideal for low-light photography and portraits.",
    productImage: "https://m.media-amazon.com/images/I/61kBwnHGUdL._SX679_.jpg",
    categoryName: "lenses",
    price: 399.99,
    discountPercent: 0,
    discountedPrice: 399.99,
    onSale: false,
    outOfStock: false,
    rating: 4.6,
    trending: true,
  },
  {
    _id: "12",
    productName: "SanDisk 128GB Extreme Pro SDXC UHS-I Memory Card",
    productDescription:
      "The SanDisk Extreme Pro SDXC UHS-I Memory Card is a high-speed card that is perfect for recording 4K video and taking high-resolution photos. It features a read speed of up to 170MB/s and a write speed of up to 90MB/s.",
    productImage: "https://m.media-amazon.com/images/I/61ao4RlOuCL._SX679_.jpg",
    categoryName: "accessories",
    price: 49.99,
    discountPercent: 10,
    discountedPrice: 44.99,
    onSale: true,
    outOfStock: false,
    rating: 2.5,
    trending: false,
  },
  {
    _id: "13",
    productName: "Vanguard BACKPACK",
    productDescription: "Camera Backpack with Customizable Interior",
    productImage: "https://m.media-amazon.com/images/I/71yUghBd0eL._SX522_.jpg",
    categoryName: "bags",
    price: 150,
    discountPercent: 20,
    discountedPrice: 130,
    onSale: true,
    outOfStock: false,
    rating: 4.6,
    trending: false,
  },
  {
    _id: "14",
    productName: "Sigma 24-70mm f/2.8 DG OS HSM Art Lens",
    productDescription:
      "A versatile and high-quality zoom lens that delivers sharp and detailed images.",
    productImage: "https://m.media-amazon.com/images/I/71kltHdtE9L._SX522_.jpg",
    categoryName: "lenses",
    price: 1299.99,
    discountPercent: 20,
    discountedPrice: 1039.99,
    onSale: true,
    outOfStock: false,
    rating: 4.8,
    trending: true,
  },
  {
    _id: "15",
    productName: "Rode USB Videomic Pro+",
    productDescription:
      "The Rode USB Videomic Pro+ Compact Directional On-Camera Shotgun Condenser Microphone is a high-quality microphone that is perfect for recording audio for video.",
    productImage: "https://m.media-amazon.com/images/I/51yFY3wSrQL._SX679_.jpg",
    categoryName: "accessories",
    price: 79.99,
    discountPercent: 15,
    discountedPrice: 66.99,
    onSale: true,
    outOfStock: false,
    rating: 4.7,
    trending: true,
  },
  {
    _id: "16",
    productName: "Joby GorillaPod SLR-Zoom Tripod",
    productDescription:
      "The Joby GorillaPod SLR-Zoom Tripod is a flexible and versatile tripod that is perfect for holding your camera steady. It features three articulating legs that can be wrapped around objects, and a ball head that allows you to quickly and easily adjust the angle of your camera.",
    productImage: "https://m.media-amazon.com/images/I/51jpuZ0zm9L._SX522_.jpg",
    categoryName: "accessories",
    price: 59.99,
    discountPercent: 20,
    discountedPrice: 47.99,
    onSale: true,
    outOfStock: false,
    rating: 4.9,
    trending: false,
  },
  {
    _id: "17",
    productName: "LensPen Lens Cleaning Pen",
    productDescription:
      "The LensPen Lens Cleaning Pen is a small and portable tool that is perfect for cleaning your lenses. It features a soft brush that removes dust and dirt, and a solvent-free cleaning fluid that removes fingerprints and smudges.",
    productImage:
      "https://lenspen.com/cdn/shop/products/LensPen1_600x.jpg?v=1628958097",
    categoryName: "accessories",
    price: 19.99,
    discountPercent: 10,
    discountedPrice: 17.99,
    onSale: true,
    outOfStock: false,
    rating: 2.8,
    trending: false,
  },
];
